'use strict';
const assert = require('assert/strict');
const { WebSocket } = require('ws');
const { startShare } = require('../lib/share-thread');
(async () => {
  const calls = [];
  const threadId = 'chosen-test-thread';
  const thread = { id: threadId, name: 'Test', turns: [{ id: 't', items: [{ type: 'userMessage', id: 'u', content: [{ type: 'text', text: 'Only the chosen chat' }] }, { type: 'reasoning', text: 'PRIVATE' }] }] };
  let reading = 0, maxReading = 0;
  let failRead = false;
  const rpc = { async request(method, params) {
    calls.push({ method, params });
    if (method === 'thread/read') {
      maxReading = Math.max(maxReading, ++reading);
      await new Promise(resolve => setTimeout(resolve, 30));
      reading--;
      if (failRead) throw new Error('Host unavailable');
      return { thread: structuredClone(thread) };
    }
    if (method === 'thread/queue/list') return {};
    if (method === 'thread/queue/add') return { queuedSubmission: { id: 'q' } };
    throw new Error('Unexpected method');
  } };
  const share = await startShare({ rpc, threadId, guestName: 'Bob' });
  try {
    const get = token => fetch(share.address + '/conversation', { headers: { authorization: `Bearer ${token}` } });
    const prompt = (token, data) => fetch(share.address + '/prompt', { method: 'POST', headers: { authorization: `Bearer ${token}`, 'content-type': 'application/json' }, body: JSON.stringify(data) });
    assert.equal((await get('wrong')).status, 401);
    const viewer = await (await get(share.viewer)).json();
    assert.equal(viewer.role, 'viewer'); assert(!JSON.stringify(viewer).includes('PRIVATE'));
    const input = { requestId: 'same-request-123', text: 'Hello', threadId: 'unrelated-thread', method: 'command/exec', role: 'owner' };
    assert.equal((await prompt(share.viewer, input)).status, 403);
    const results = await Promise.all([prompt(share.contributor, input), prompt(share.contributor, input)]);
    assert(results.every(r => r.status === 202));
    assert.equal(calls.filter(c => c.method === 'thread/queue/add').length, 1);
    const queued = calls.find(c => c.method === 'thread/queue/add').params;
    assert.equal(queued.threadId, threadId); assert.match(queued.input[0].text, /participant: Bob/);
    assert.equal((await prompt(share.contributor, { ...input, text: 'changed' })).status, 409);
    assert.equal((await prompt(share.contributor, { ...input, requestId: 'large-request', text: 'x'.repeat(18000) })).status, 400);
    const waitFor = async (condition, timeout = 2000) => {
      const deadline = Date.now() + timeout;
      while (!condition()) {
        assert(Date.now() < deadline, 'Timed out waiting for stream event');
        await new Promise(resolve => setTimeout(resolve, 10));
      }
    };
    const streams = [];
    const stream = async token => {
      const ws = new WebSocket(share.address.replace('http:', 'ws:') + '/events');
      const result = { events: [], done: false, ws };
      streams.push(result);
      ws.on('message', frame => result.events.push(JSON.parse(frame.toString())));
      ws.on('close', code => { result.done = true; result.code = code; });
      await new Promise((resolve, reject) => { ws.once('open', resolve); ws.once('error', reject); });
      if (token !== undefined) ws.send(JSON.stringify({ token }));
      return result;
    };
    assert.equal((await fetch(share.address + '/events')).status, 401);
    const unauthorized = await stream();
    await new Promise(resolve => setTimeout(resolve, 100));
    assert.equal(unauthorized.events.length, 0, 'No chat data before authentication');
    unauthorized.ws.send(JSON.stringify({ token: 'wrong' }));
    await waitFor(() => unauthorized.done);
    assert.equal(unauthorized.code, 4401);
    assert.equal(unauthorized.events.length, 0);
    const expiredAuth = await stream();
    await waitFor(() => expiredAuth.done, 6000);
    assert.equal(expiredAuth.code, 4401);
    assert.equal(expiredAuth.events.length, 0);
    const oversizedAuth = await stream();
    oversizedAuth.ws.send('x'.repeat(2049));
    await waitFor(() => oversizedAuth.done);
    assert.equal(oversizedAuth.events.length, 0);
    assert.notEqual(oversizedAuth.code, 1000);
    const [contributorStream, viewerStream] = await Promise.all([stream(share.contributor), stream(share.viewer)]);
    await waitFor(() => [contributorStream, viewerStream].every(s => s.events.length === 1));
    assert.equal(contributorStream.events[0].event, 'snapshot');
    assert.equal(viewerStream.events[0].data.role, 'viewer');
    assert(!JSON.stringify(contributorStream.events).includes('PRIVATE'));
    const beforePolls = calls.filter(c => c.method === 'thread/read').length;
    await new Promise(resolve => setTimeout(resolve, 620));
    assert([contributorStream, viewerStream].every(s => s.events.length === 1), 'Unchanged history must not be retransmitted');
    const polls = calls.filter(c => c.method === 'thread/read').length - beforePolls;
    assert(polls >= 2 && polls <= 3, `Two listeners should share backend polling; got ${polls}`);
    assert.equal(maxReading, 1);
    thread.turns.push({ id: 'new-turn', status: 'inProgress', items: [{ type: 'agentMessage', id: 'answer', text: 'Live reply' }] });
    await waitFor(() => [contributorStream, viewerStream].every(s => s.events.length === 2));
    const delta = contributorStream.events[1];
    assert.equal(delta.event, 'update');
    assert.deepEqual(delta.data.turns.map(t => t.id), ['new-turn']);
    assert.deepEqual(delta.data.removedTurnIds, []);
    thread.turns[1].items[0].text = 'Live reply finished';
    thread.turns[1].status = 'completed';
    await waitFor(() => contributorStream.events.length === 3);
    assert.equal(contributorStream.events[2].data.turns[0].items[0].text, 'Live reply finished');
    thread.turns.reverse();
    await waitFor(() => contributorStream.events.length === 4);
    assert.equal(contributorStream.events[3].event, 'snapshot');
    thread.turns.pop();
    await waitFor(() => contributorStream.events.length === 5);
    assert.deepEqual(contributorStream.events[4].data.removedTurnIds, ['t']);
    failRead = true;
    await waitFor(() => contributorStream.events.at(-1).event === 'unavailable');
    const outageCount = contributorStream.events.length;
    await new Promise(resolve => setTimeout(resolve, 1150));
    assert.equal(contributorStream.events.length, outageCount, 'Repeated failures do not flood the stream');
    failRead = false;
    await waitFor(() => contributorStream.events.at(-1).event === 'available');
    assert.equal(contributorStream.events.length, outageCount + 1, 'Unchanged history still announces backend recovery');
    viewerStream.ws.close();
    await waitFor(() => viewerStream.done);
    const reconnected = await stream(share.viewer);
    await waitFor(() => reconnected.events.length === 1);
    assert.equal(reconnected.events[0].event, 'snapshot');
    assert.deepEqual(reconnected.events[0].data.turns.map(t => t.id), ['new-turn']);
    share.revoke(share.contributor);
    assert.equal((await get(share.contributor)).status, 401);
    await waitFor(() => contributorStream.done);
    assert.equal(contributorStream.code, 4401);
    const revoked = await stream(share.contributor);
    await waitFor(() => revoked.done);
    assert.equal(revoked.code, 4401);
    assert.equal(revoked.events.length, 0);
    reconnected.ws.close();
    await waitFor(() => reconnected.done);
    console.log('PASS thread sharing: authorization, viewer restrictions, thread isolation, retry deduplication, revocation, private-item filtering, authenticated WebSockets, shared polling, incremental updates, reorder reset, streaming revocation, outage recovery, reconnect snapshots');
  } finally { await share.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
